/***** ISO 3 numeric codes *****/

program code_convert_country_long
version 1.0

syntax , from_cl(passthru) to_cl(passthru)

tempvar _from_clean
gen `_from_clean' = lower(`from_cl')
replace `_from_clean' = substr(`from',"the ","",.)

tempvar _`_from_clean'
gen `_from_clean' = ""


replace `_names_std' = "Afghanistan" if `_from_clean' == "afghanistan" | `_from_clean' == "afghan" | `_from_clean' == "afganistan"
replace `_names_std' = "Albania" if `_from_clean' == "albania"
replace `_names_std' = "Algeria" if `_from_clean' == "algeria"
replace `_names_std' = "American Samoa" if `_from_clean' == "american samoa" | `_from_clean' == "eastern samoa" | `_from_clean' == "samoa american"
replace `_names_std' = "Andorra" if `_from_clean' == "andorra"
replace `_names_std' = "Angola" if `_from_clean' == "angola"
replace `_names_std' = "Anguilla" if `_from_clean' == "anguilla"
replace `_names_std' = "Antigua and Barbuda" if `_from_clean' == "antigua and barbuda" | `_from_clean' == "antigua barbuda" | `_from_clean' == "antigua barbuda"
replace `_names_std' = "Argentina" if `_from_clean' == "argentina" | `_from_clean' == "argent"
replace `_names_std' = "Armenia" if `_from_clean' == "armenia"
replace `_names_std' = "Aruba" if `_from_clean' == "aruba"
replace `_names_std' = "Australia" if `_from_clean' == "australia" | `_from_clean' == "austral"
replace `_names_std' = "Austria" if `_from_clean' == "austria"
replace `_names_std' = "Austria-Hungary" if `_from_clean' == "austriahungary"
replace `_names_std' = "Azerbaijan" if `_from_clean' == "azerbaijan"
replace `_names_std' = "Azores" if `_from_clean' == "azores"
replace `_names_std' = "Baden" if `_from_clean' == "baden"
replace `_names_std' = "Bahamas" if `_from_clean' == "bahamas"
replace `_names_std' = "Bahrain" if `_from_clean' == "bahrain"
replace `_names_std' = "Bangladesh" if `_from_clean' == "bangladesh" | `_from_clean' == "bngldsh"
replace `_names_std' = "Barbados" if `_from_clean' == "barbados" | `_from_clean' == "barbado"
replace `_names_std' = "Bavaria" if `_from_clean' == "bavaria"
replace `_names_std' = "Belarus" if `_from_clean' == "belarus" | `_from_clean' == "byelorussia" | `_from_clean' == "belarus byelorussia"
replace `_names_std' = "Belgium" if `_from_clean' == "belgium"
replace `_names_std' = "Belize" if `_from_clean' == "belize"
replace `_names_std' = "Benin" if `_from_clean' == "benin" | `_from_clean' == "dahomey" | `_from_clean' == "benin/dahomey" | `_from_clean' == "benin dahomey"
replace `_names_std' = "Bermuda" if `_from_clean' == "bermuda"
replace `_names_std' = "Bhutan" if `_from_clean' == "bhutan"
replace `_names_std' = "Bolivia" if `_from_clean' == "bolivia"
replace `_names_std' = "Bonaire" if `_from_clean' == "bonaire"
replace `_names_std' = "Bosnia and Herzegovina" if `_from_clean' == "bosnia and herzegovina" | `_from_clean' == "bosnia herzegovina" | `_from_clean' == "bosnia/herzogovina" | `_from_clean' == "bosnia" | `_from_clean' == "bosnia/herzegovina" | `_from_clean' == "bosnia and hercegovina" | `_from_clean' == "bosnia hercegovina" | `_from_clean' == "bosnia/hercogovina" | `_from_clean' == "bosnia hercegovina" | `_from_clean' == "bosnia/hercegovina" | `_from_clean' == "bosniahercegovina" | `_from_clean' == "bosniaherzegovina" | `_from_clean' == "bosniaherzegov" | `_from_clean' == "bosniahercegov" | `_from_clean' == "bosnia herzegov" | `_from_clean' == "bosnia hercegov" | `_from_clean' == "bosniaher"
replace `_names_std' = "Botswana" if `_from_clean' == "botswana"
replace `_names_std' = "Brazil" if `_from_clean' == "brazil"
replace `_names_std' = "Brunei" if `_from_clean' == "brunei" | `_from_clean' == "brunei darussalam"
replace `_names_std' = "Bulgaria" if `_from_clean' == "bulgaria"
replace `_names_std' = "Burkina Faso" if `_from_clean' == "burkina faso" | `_from_clean' == "upper volta" | `_from_clean' == "burkina faso upper volta" | `_from_clean' == "upp" | `_from_clean' == "hvo" | `_from_clean' == "burkina"
replace `_names_std' = "Burundi" if `_from_clean' == "burundi"
replace `_names_std' = "Cambodia" if `_from_clean' == "cambodia" | `_from_clean' == "kampuchea" | `_from_clean' == "cambodia kampuchea" | `_from_clean' == "cambod" | `_from_clean' == "democratic kampuchea"
replace `_names_std' = "Cameroon" if `_from_clean' == "cameroon" | `_from_clean' == "cameroun"
replace `_names_std' = "Canada" if `_from_clean' == "canada"
replace `_names_std' = "Canary Islands" if `_from_clean' == "canary islands"
replace `_names_std' = "Cape Verde" if `_from_clean' == "cape verde"
replace `_names_std' = "Cayman Islands" if `_from_clean' == "cayman islands" | `_from_clean' == "cayman is"
replace `_names_std' = "Central African Republic" if `_from_clean' == "central african republic" | `_from_clean' == "c african rep" | `_from_clean' == "central african empire" | `_from_clean' == "c_africa" | `_from_clean' == "cen african rep"
replace `_names_std' = "Chad" if `_from_clean' == "chad"
replace `_names_std' = "Channel Islands" if `_from_clean' == "channel islands"
replace `_names_std' = "Chile" if `_from_clean' == "chile"
replace `_names_std' = "China" if `_from_clean' == "china" | `_from_clean' == "china mainland"
replace `_names_std' = "Christmas Islands" if `_from_clean' == "christmas islands" | `_from_clean' == "christmas is" | `_from_clean' == "christmas island"
replace `_names_std' = "Cocos Islands" if `_from_clean' == "cocos islands" | `_from_clean' == "cocos keeling islands" | `_from_clean' == "cocos is"
replace `_names_std' = "Colombia" if `_from_clean' == "colombia"
replace `_names_std' = "Comoros" if `_from_clean' == "comoros"
replace `_names_std' = "Democratic Republic of Congo" if `_from_clean' == "democratic republic of congo" | `_from_clean' == "dem rep congo" | `_from_clean' == "congo dem r" | `_from_clean' == "zaire congo kinshasa" | `_from_clean' == "congo dr zaire" | `_from_clean' == "congo dem rep" | `_from_clean' == "zaire/dem rep of congo" | `_from_clean' == "congo droc" | `_from_clean' == "congo kinshasa" | `_from_clean' == "zaire" | `_from_clean' == "zaire democratic republic of congo" | `_from_clean' == "congo democratic republic of" | `_from_clean' == "congo democratic rep of"
replace `_names_std' = "Congo" if `_from_clean' == "congo" | `_from_clean' == "rep of congo" | `_from_clean' == "congo rep of" | `_from_clean' == "congo brazaville" | `_from_clean' == "congo brazzaville" | `_from_clean' == "congo rep" | `_from_clean' == "congo brazzaville" | `_from_clean' == "congo brazaville" | `_from_clean' == "congo brazaville" | `_from_clean' == "congo brazzaville" | `_from_clean' == "congo republic of"  | `_from_clean' == "congo roc"
replace `_names_std' = "Cook Islands" if `_from_clean' == "cook islands" | `_from_clean' == "cook is"
replace `_names_std' = "Costa Rica" if `_from_clean' == "costa rica" | `_from_clean' == "costarica" | `_from_clean' == "cos_rica"
replace `_names_std' = "Croatia" if `_from_clean' == "croatia"
replace `_names_std' = "Cuba" if `_from_clean' == "cuba"
replace `_names_std' = "Curacao" if `_from_clean' == "curacao"
replace `_names_std' = "Cyprus" if `_from_clean' == "cyprus"
replace `_names_std' = "Czech Republic" if `_from_clean' == "czech republic" | `_from_clean' == "czechrep" | `_from_clean' == "czech rep" | `_from_clean' == "czech republic "
replace `_names_std' = "Czechoslovakia" if `_from_clean' == "czechoslovakia" | `_from_clean' == "czechoslovakia former" | `_from_clean' == "czecho"
replace `_names_std' = "Denmark" if `_from_clean' == "denmark"
replace `_names_std' = "Djibouti" if `_from_clean' == "djibouti"
replace `_names_std' = "Dominica" if `_from_clean' == "dominica" | `_from_clean' == "dominica is"
replace `_names_std' = "Dominican Republic" if `_from_clean' == "dominican republic" | `_from_clean' == "dominican rep" | `_from_clean' == "dom_rep"
replace `_names_std' = "Easter Island" if `_from_clean' == "easter island"
replace `_names_std' = "Ecuador" if `_from_clean' == "ecuador"
replace `_names_std' = "Egypt" if `_from_clean' == "egypt" | `_from_clean' == "uar" | `_from_clean' == "egypt/uar" | `_from_clean' == "egypt uar" | `_from_clean' == "united arab republic" | `_from_clean' == "egypt arab rep"
replace `_names_std' = "El Salvador" if `_from_clean' == "el salvador" | `_from_clean' == "salvador" | `_from_clean' == "salvadr"
replace `_names_std' = "Equatorial Guinea" if `_from_clean' == "equatorial guinea" | `_from_clean' == "eq_gnea" | `_from_clean' == "guinea equatorial" | `_from_clean' == "eq guinea"
replace `_names_std' = "Eritrea" if `_from_clean' == "eritrea"
replace `_names_std' = "Estonia" if `_from_clean' == "estonia"
replace `_names_std' = "Ethiopia" if `_from_clean' == "ethiopia" | `_from_clean' == "ethiopia 8993"
replace `_names_std' = "European Union" if `_from_clean' == "european union" | `_from_clean' == "eu" | `_from_clean' == "european community"
replace `_names_std' = "Faeroe Islands" if `_from_clean' == "faeroe islands" | `_from_clean' == "faroe islands" | `_from_clean' == "faeroe is" | `_from_clean' == "faroe is"
replace `_names_std' = "Falkland Islands" if `_from_clean' == "falkland islands" | `_from_clean' == "falkland islands malvinas" | `_from_clean' == "malvinas" | `_from_clean' == "falkland is" | `_from_clean' == "falk_is"
replace `_names_std' = "Fiji" if `_from_clean' == "fiji"
replace `_names_std' = "Finland" if `_from_clean' == "finland"
replace `_names_std' = "France" if `_from_clean' == "france"
replace `_names_std' = "French Polynesia" if `_from_clean' == "french polynesia" | `_from_clean' == "fr polynesia"
replace `_names_std' = "Gabon" if `_from_clean' == "gabon"
replace `_names_std' = "Gambia" if `_from_clean' == "gambia"
replace `_names_std' = "Georgia" if `_from_clean' == "georgia"
replace `_names_std' = "German Democratic Republic" if `_from_clean' == "german democratic republic" | `_from_clean' == "east germany" | `_from_clean' == "german democratic rep" | `_from_clean' == "german democratic republic former" | `_from_clean' == "germany dr" | `_from_clean' == "german_e" | `_from_clean' == "germany east"
replace `_names_std' = "Germany" if `_from_clean' == "germany"	| `_from_clean' == "prussia" | `_from_clean' == "germany/prussia" | `_from_clean' == "german federal republic" | `_from_clean' == "west germany" | `_from_clean' == "germany federal republic of" | `_from_clean' == "federal republic of germany" | `_from_clean' == "german" | `_from_clean' == "germany west"
replace `_names_std' = "Ghana" if `_from_clean' == "ghana"
replace `_names_std' = "Gibraltar" if `_from_clean' == "gibraltar" | `_from_clean' == "gilbraltar" | `_from_clean' == "gilbralt"
replace `_names_std' = "Greece" if `_from_clean' == "greece"
replace `_names_std' = "Greenland" if `_from_clean' == "greenland" | `_from_clean' == "greenld"
replace `_names_std' = "Grenada" if `_from_clean' == "grenada" | `_from_clean' == "grenada is"
replace `_names_std' = "Guadeloupe" if `_from_clean' == "guadeloupe" | `_from_clean' == "guadlpe"
replace `_names_std' = "Guam" if `_from_clean' == "guam"
replace `_names_std' = "Guatemala" if `_from_clean' == "guatemala" | `_from_clean' == "guatmala"
replace `_names_std' = "Guinea" if `_from_clean' == "guinea"
replace `_names_std' = "Guinea-Bissau" if `_from_clean' == "guineabissau" | `_from_clean' == "guinea bissau" | `_from_clean' == "g bissau" | `_from_clean' == "g_bissau" | `_from_clean' == "g_bisau"
replace `_names_std' = "Guyana" if `_from_clean' == "guyana"
replace `_names_std' = "French Guiana" if `_from_clean' == "french guiana" | `_from_clean' == "guiana" | `_from_clean' == "guyana french" | `_from_clean' == "fr_guian" | `_from_clean' == "guiana french"
replace `_names_std' = "Haiti" if `_from_clean' == "haiti"
replace `_names_std' = "Hanover" if `_from_clean' == "hanover"
replace `_names_std' = "Hesse Electoral" if `_from_clean' == "hesse electoral"
replace `_names_std' = "Hesse Grand Ducal" if `_from_clean' == "hesse grand ducal"
replace `_names_std' = "Honduras" if `_from_clean' == "honduras" | `_from_clean' == "hondura"
replace `_names_std' = "Hong Kong" if `_from_clean' == "hong kong" | `_from_clean' == "china hong kong special administrative region" | `_from_clean' == "hongkong" | `_from_clean' == "hong kong special administrative region of china" | `_from_clean' == "hong kong china"
replace `_names_std' = "Hungary" if `_from_clean' == "hungary"
replace `_names_std' = "Iceland" if `_from_clean' == "iceland"
replace `_names_std' = "India" if `_from_clean' == "india"
replace `_names_std' = "Indonesia" if `_from_clean' == "indonesia" | `_from_clean' == "indones"
replace `_names_std' = "Iran" if `_from_clean' == "iran" | `_from_clean' == "persia" | `_from_clean' == "iran persia" | `_from_clean' == "iran islamic republic of" | `_from_clean' == "iran islamic republic of" | `_from_clean' == "iran islamic rep"
replace `_names_std' = "Iraq" if `_from_clean' == "iraq"
replace `_names_std' = "Ireland" if `_from_clean' == "ireland" | `_from_clean' == "eire"
replace `_names_std' = "Israel" if `_from_clean' == "israel" | `_from_clean' == "israel 1989"
replace `_names_std' = "Italy" if `_from_clean' == "italy" | `_from_clean' == "italy/sardinia"
replace `_names_std' = "Cote d'Ivoire" if `_from_clean' == "cote d'ivoire" | `_from_clean' == "ivory coast" | `_from_clean' == "ivy_cst" | `_from_clean' == "c�te d'ivoire" | `_from_clean' == "cote d`ivoire"
replace `_names_std' = "Jamaica" if `_from_clean' == "jamaica"
replace `_names_std' = "Japan" if `_from_clean' == "japan"
replace `_names_std' = "Jordan" if `_from_clean' == "jordan" | `_from_clean' == "jordon"
replace `_names_std' = "Kazakhstan" if `_from_clean' == "kazakhstan" | `_from_clean' == "kazakstan"
replace `_names_std' = "Kenya" if `_from_clean' == "kenya"
replace `_names_std' = "Kyrgyz Republic" if `_from_clean' == "kyrgyz republic"	| `_from_clean' == "kyrghyz republic" | `_from_clean' == "kez" | `_from_clean' == "kirgizia" | `_from_clean' == "kirghistan" | `_from_clean' == "kyrgyzstan" | `_from_clean' == "kyrgyz rep" | `_from_clean' == "kyrgystan"
replace `_names_std' = "Kiribati" if `_from_clean' == "kiribati" | `_from_clean' == "gilbert islands"
replace `_names_std' = "South Korea" if `_from_clean' == "south korea" | `_from_clean' == "s korea" | `_from_clean' == "korea" | `_from_clean' == "korea republic of" | `_from_clean' == "korea_s" | `_from_clean' == "korea rep of" | `_from_clean' == "korea rep" | `_from_clean' == "korea south" | `_from_clean' == "republic of korea" | `_from_clean' == "korea south republic of" | `_from_clean' == "republic of korea seoul"
replace `_names_std' = "North Korea" if `_from_clean' == "north korea" | `_from_clean' == "korea dem people's rep" | `_from_clean' == "democratic people's republic of korea" | `_from_clean' == "korea democratic people's republic of" | `_from_clean' == "n korea" | `_from_clean' == "korea_n" | `_from_clean' == "korea north" | `_from_clean' == "korea demo people's rep of"
replace `_names_std' = "Kuwait" if `_from_clean' == "kuwait"
replace `_names_std' = "Laos" if `_from_clean' == "laos" | `_from_clean' == "lao people's democratic republic" | `_from_clean' == "lao" | `_from_clean' == "lao pdr"
replace `_names_std' = "Latvia" if `_from_clean' == "latvia"
replace `_names_std' = "Lebanon" if `_from_clean' == "lebanon"
replace `_names_std' = "Leeward Islands" if `_from_clean' == "leeward islands"
replace `_names_std' = "Lesotho" if `_from_clean' == "lesotho"
replace `_names_std' = "Liberia" if `_from_clean' == "liberia"
replace `_names_std' = "Libya" if `_from_clean' == "libya" | `_from_clean' == "libyan arab jamahiriya"
replace `_names_std' = "Liechtenstein" if `_from_clean' == "liechtenstein"
replace `_names_std' = "Lithuania" if `_from_clean' == "lithuania"
replace `_names_std' = "Luxembourg" if `_from_clean' == "luxembourg"
replace `_names_std' = "Macao" if `_from_clean' == "macao" | `_from_clean' == "china macao special administrative region" | `_from_clean' == "macau" | `_from_clean' == "macao special administrative region of china" | `_from_clean' == "macao china"
replace `_names_std' = "Macedonia" if `_from_clean' == "macedonia" | `_from_clean' == "former yugoslav republic of macedonia" | `_from_clean' == "macedonia fyr" | `_from_clean' == "macedonia tfyr"
replace `_names_std' = "Madagascar" if `_from_clean' == "madagascar" | `_from_clean' == "malagasy" | `_from_clean' == "malagasy republic" | `_from_clean' == "madagas"
replace `_names_std' = "Malawi" if `_from_clean' == "malawi"
replace `_names_std' = "Malaysia" if `_from_clean' == "malaysia"
replace `_names_std' = "Maldives" if `_from_clean' == "maldives" | `_from_clean' == "maldive islands" | `_from_clean' == "maldive is"
replace `_names_std' = "Mali" if `_from_clean' == "mali"
replace `_names_std' = "Malta" if `_from_clean' == "malta"
replace `_names_std' = "Marshall Islands" if `_from_clean' == "marshall islands" | `_from_clean' == "marshall is"
replace `_names_std' = "Martinique" if `_from_clean' == "martinique"
replace `_names_std' = "Mauritania" if `_from_clean' == "mauritania" | `_from_clean' == "mauritn"
replace `_names_std' = "Mauritius" if `_from_clean' == "mauritius" | `_from_clean' == "mritius"
replace `_names_std' = "Mayotte" if `_from_clean' == "mayotte" | `_from_clean' == "may"
replace `_names_std' = "Meckelnburg Schwerin" if `_from_clean' == "meckelnburg schwerin"
replace `_names_std' = "Mexico" if `_from_clean' == "mexico"
replace `_names_std' = "Micronesia" if `_from_clean' == "micronesia" | `_from_clean' == "federated states of micronesia" | `_from_clean' == "micronesia federated states of" | `_from_clean' == "f st micronesia" | `_from_clean' == "micronesia fed sts"
replace `_names_std' = "Modena" if `_from_clean' == "modena"
replace `_names_std' = "Moldova" if `_from_clean' == "moldova"	 | `_from_clean' == "moldavia" | `_from_clean' == "moldova moldavia" | `_from_clean' == "republic of moldova" | `_from_clean' == "moldova republic of"
replace `_names_std' = "Monaco" if `_from_clean' == "monaco"
replace `_names_std' = "Mongolia" if `_from_clean' == "mongolia" | `_from_clean' == "mongola"
replace `_names_std' = "Montenegro" if `_from_clean' == "montenegro"
replace `_names_std' = "Montserrat" if `_from_clean' == "montserrat" | `_from_clean' == "montserrat is"
replace `_names_std' = "Morocco" if `_from_clean' == "morocco"
replace `_names_std' = "Mozambique" if `_from_clean' == "mozambique" | `_from_clean' == "mozambq"
replace `_names_std' = "Myanmar" if `_from_clean' == "myanmar"	| `_from_clean' == "burma" | `_from_clean' == "bur" | `_from_clean' == "myanmar burma" | `_from_clean' == "burma myanmar" | `_from_clean' == "burma/myanmar" | `_from_clean' == "myanmar/burma" | `_from_clean' == "myanmar exburma"
replace `_names_std' = "Namibia" if `_from_clean' == "namibia"
replace `_names_std' = "Nauru" if `_from_clean' == "nauru"
replace `_names_std' = "Nepal" if `_from_clean' == "nepal"
replace `_names_std' = "Netherlands" if `_from_clean' == "nerlands" | `_from_clean' == "holland" | `_from_clean' == "nethlds"
replace `_names_std' = "Netherlands Antilles" if `_from_clean' == "nerlands antilles" | `_from_clean' == "nerlands ant" | `_from_clean' == "n_antil" | `_from_clean' == "neth ant" | `_from_clean' == "n_antilles" | `_from_clean' == "antilles nerlands"
replace `_names_std' = "New Caledonia" if `_from_clean' == "new caledonia" | `_from_clean' == "new_cale" | `_from_clean' == "new cale" | `_from_clean' == "n caledonia" | `_from_clean' == "n_caledonia"
replace `_names_std' = "New Zealand" if `_from_clean' == "new zealand" | `_from_clean' == "new_zeal"
replace `_names_std' = "Nicaragua" if `_from_clean' == "nicaragua" | `_from_clean' == "nicaraga"
replace `_names_std' = "Niger" if `_from_clean' == "niger"
replace `_names_std' = "Nigeria" if `_from_clean' == "nigeria"
replace `_names_std' = "Niue" if `_from_clean' == "niue"
replace `_names_std' = "Norway" if `_from_clean' == "norway"
replace `_names_std' = "Oman" if `_from_clean' == "oman"
replace `_names_std' = "Pakistan" if `_from_clean' == "pakistan"
replace `_names_std' = "Palau" if `_from_clean' == "palau"
replace `_names_std' = "Palestine" if `_from_clean' == "palestine" | `_from_clean' == "west bank and gaza" | `_from_clean' == "palestinian administration areas / west bank and gaza" | `_from_clean' == "palestinian administration areas" | `_from_clean' == "palestinian territory"
replace `_names_std' = "Panama" if `_from_clean' == "panama"
replace `_names_std' = "Papua New Guinea" if `_from_clean' == "papua new guinea" | `_from_clean' == "papua ng" | `_from_clean' == "pap new guinea" | `_from_clean' == "p new guinea" | `_from_clean' == "new guinea" | `_from_clean' == "papua and new guinea" | `_from_clean' == "papua n g" | `_from_clean' == "papua new guin" | `_from_clean' == "new_guinea" | `_from_clean' == "new_guin"
replace `_names_std' = "Paraguay" if `_from_clean' == "paraguay" | `_from_clean' == "paragua"
replace `_names_std' = "Parma" if `_from_clean' == "parma"
replace `_names_std' = "Peru" if `_from_clean' == "peru"
replace `_names_std' = "Philippines" if `_from_clean' == "philippines" | `_from_clean' == "phil"
replace `_names_std' = "Poland" if `_from_clean' == "poland"
replace `_names_std' = "Portugal" if `_from_clean' == "portugal"
replace `_names_std' = "Puerto Rico" if `_from_clean' == "puerto rico"
replace `_names_std' = "Qatar" if `_from_clean' == "qatar"
replace `_names_std' = "Reunion" if `_from_clean' == "reunion" | `_from_clean' == "r�union"
replace `_names_std' = "Romania" if `_from_clean' == "romania"	| `_from_clean' == "rumania"
replace `_names_std' = "Russia" if `_from_clean' == "russia" | `_from_clean' == "ussr" | `_from_clean' == "russian federation" | `_from_clean' == "sun" | `_from_clean' == "russia/soviet union" | `_from_clean' == "union of soviet socialist republics former" | `_from_clean' == "union of soviet socialist republics" | `_from_clean' == "russia russian federation" | `_from_clean' == "union of soviet socialist republics ussr" | `_from_clean' == "ussr soviet union"
replace `_names_std' = "Rwanda" if `_from_clean' == "rwanda"
replace `_names_std' = "Saint Helena" if `_from_clean' == "saint helena" |  `_from_clean' == "st helena" | `_from_clean' == "s_helna"
replace `_names_std' = "Saint Kitts and Nevis" if `_from_clean' == "saint kitts and nevis" | `_from_clean' == "st kittsnevis" | `_from_clean' == "st_k_nev" | `_from_clean' == "st kitts and nevis" | `_from_clean' == "saint kitts nevis" | `_from_clean' == "saint kittsnevis"
replace `_names_std' = "Saint Lucia" if `_from_clean' == "saint lucia"	| `_from_clean' == "st lucia" | `_from_clean' == "st lucia is"
replace `_names_std' = "Saint Pierre and Miquelon" if `_from_clean' == "saint pierre and miquelon" | `_from_clean' == "saint pierre miquelon" | `_from_clean' == "st pierre miq"
replace `_names_std' = "Saint Vincent and the Grenadines" if `_from_clean' == "saint vincent and grenadines" | `_from_clean' == "st vincent grenadines" | `_from_clean' == "saint vincent" | `_from_clean' == "st vinc gren" | `_from_clean' == "st vinc and gren" | `_from_clean' == "st vincent and grenadines" | `_from_clean' == "saint vincent grenadines"
replace `_names_std' = "San Marino" if `_from_clean' == "san marino"
replace `_names_std' = "Sao Tome and Principe" if `_from_clean' == "sao tome and principe" | `_from_clean' == "sao tome principe" | `_from_clean' == "sao tomeprincipe" | `_from_clean' == "sao tome and prin" | `_from_clean' == "sao tome prin"
replace `_names_std' = "Saudi Arabia" if `_from_clean' == "saudi arabia" | `_from_clean' == "sd_arab" | `_from_clean' == "arabia saudi"
replace `_names_std' = "Saxony" if `_from_clean' == "saxony"
replace `_names_std' = "Senegal" if `_from_clean' == "senegal"
replace `_names_std' = "Seychelles" if `_from_clean' == "seychelles" | `_from_clean' == "seychel"
replace `_names_std' = "Sierra Leone" if `_from_clean' == "sierra leone" | `_from_clean' == "sier_ln"
replace `_names_std' = "Singapore" if `_from_clean' == "singapore" | `_from_clean' == "singapr"
replace `_names_std' = "Slovak Republic" if `_from_clean' == "slovak republic" | `_from_clean' == "slovakia"
replace `_names_std' = "Slovenia" if `_from_clean' == "slovenia"
replace `_names_std' = "Solomon Islands" if `_from_clean' == "solomon islands" | `_from_clean' == "solomon is"
replace `_names_std' = "Somalia" if `_from_clean' == "somalia"
replace `_names_std' = "South Africa" if `_from_clean' == "south africa" | `_from_clean' == "s_africa" | `_from_clean' == "s africa"
replace `_names_std' = "South Sudan" if `_from_clean' == "south sudan" | `_from_clean' == "republic of south sudan" | `_from_clean' == "rep of south sudan" | `_from_clean' == "rep of s sudan" | `_from_clean' == "south sudan rep of" | `_from_clean' == "south sudan republic of"
replace `_names_std' = "Spain" if `_from_clean' == "spain"
replace `_names_std' = "Sri Lanka" if `_from_clean' == "sri lanka" | `_from_clean' == "ceylon" | `_from_clean' == "sri lanka ceylon" | `_from_clean' == "sri_lka" | `_from_clean' == "sri lanka exceilan"
replace `_names_std' = "Sudan" if `_from_clean' == "sudan"
replace `_names_std' = "Suriname" if `_from_clean' == "suriname" | `_from_clean' == "surinam"
replace `_names_std' = "Swaziland" if `_from_clean' == "swaziland"
replace `_names_std' = "Sweden" if `_from_clean' == "sweden"
replace `_names_std' = "Switzerland" if `_from_clean' == "switzerland" | `_from_clean' == "switzld"
replace `_names_std' = "Syria" if `_from_clean' == "syria" | `_from_clean' == "syrian arab republic"
replace `_names_std' = "Tajikistan" if `_from_clean' == "tajikistan" | `_from_clean' == "tadzhikistan"
replace `_names_std' = "Taiwan" if `_from_clean' == "taiwan" | `_from_clean' == "roc" | `_from_clean' == "taipei" | `_from_clean' == "oan" | `_from_clean' == "china taiwan" | `_from_clean' == "taiwan province of china" | `_from_clean' == "formosa" | `_from_clean' == "chinataiwanformosa" | `_from_clean' == "chinese taipei"
replace `_names_std' = "Tanzania" if `_from_clean' == "tanzania" | `_from_clean' == "tanganyika" | `_from_clean' == "tanzania/tanganyika" | `_from_clean' == "united republic of tanzania" | `_from_clean' == "tanzania united republic of"
replace `_names_std' = "Thailand" if `_from_clean' == "thailand"
replace `_names_std' = "Timor" if `_from_clean' == "timor" | `_from_clean' == "east timor leste" | `_from_clean' == "timor leste" | `_from_clean' == "timorleste" | `_from_clean' == "east timor timorleste" | `_from_clean' == "timorleste east timor" | `_from_clean' == "east timor"
replace `_names_std' = "Togo" if `_from_clean' == "togo"
replace `_names_std' = "Tonga" if `_from_clean' == "tonga"
replace `_names_std' = "Trinidad and Tobago" if `_from_clean' == "trinidad and tobago"	| `_from_clean' == "trinidad tob" | `_from_clean' == "trinidad tobago" | `_from_clean' == "trinidad" | `_from_clean' == "trin and tobago" | `_from_clean' == "trin tobago"
replace `_names_std' = "Tunisia" if `_from_clean' == "tunisia"
replace `_names_std' = "Turkey" if `_from_clean' == "turkey" | `_from_clean' == "ottoman empire" | `_from_clean' == "turkey/ottoman empire"
replace `_names_std' = "Turkmenistan" if `_from_clean' == "turkmenistan" | `_from_clean' == "turkmenia" | `_from_clean' == "turkmenist"
replace `_names_std' = "Turks and Caicos Islands" if `_from_clean' == "turks and caicos islands" | `_from_clean' == "turks caicos islands" | `_from_clean' == "turks caicos" | `_from_clean' == "turks and caicos" | `_from_clean' == "turks caic is"
replace `_names_std' = "Tuscany" if `_from_clean' == "tuscany"
replace `_names_std' = "Tuvalu" if `_from_clean' == "tuvalu"
replace `_names_std' = "Two Sicilies" if `_from_clean' == "two sicilies"
replace `_names_std' = "Uganda" if `_from_clean' == "uganda"
replace `_names_std' = "Ukraine" if `_from_clean' == "ukraine"
replace `_names_std' = "United Arab Emirates" if `_from_clean' == "united arab emirates" | `_from_clean' == "unit arab em" | `_from_clean' == "united arab emerates" | `_from_clean' == "united ae" | `_from_clean' == "united a e" | `_from_clean' == "arab emirates" | `_from_clean' == "arab_em" | `_from_clean' == "uae" | `_from_clean' == "united arab em"
replace `_names_std' = "United Kingdom" if `_from_clean' == "united kingdom" | `_from_clean' == "uk" | `_from_clean' == "great britain" | `_from_clean' == "britain" | `_from_clean' == "ukingdom"
replace `_names_std' = "United States" if `_from_clean' == "united states" | `_from_clean' == "usa" | `_from_clean' == "us" | `_from_clean' == "united states of america"
replace `_names_std' = "Uruguay" if `_from_clean' == "uruguay"
replace `_names_std' = "Uzbekistan" if `_from_clean' == "uzbekistan"
replace `_names_std' = "Vanuatu" if `_from_clean' == "vanuatu" | `_from_clean' == "new hebrides"
replace `_names_std' = "Vatican" if `_from_clean' == "vatican" | `_from_clean' == "papal states" | `_from_clean' == "holy see" | `_from_clean' == "vatican city" | `_from_clean' == "holy see vatican city state" | `_from_clean' == "vatican city state holy see"
replace `_names_std' = "Venezuela" if `_from_clean' == "venezuela" | `_from_clean' == "venez"| `_from_clean' == "venezuela rb"
replace `_names_std' = "Vietnam" if `_from_clean' == "vietnam" | `_from_clean' == "vnmn" | `_from_clean' == "vietnam democratic rep" | `_from_clean' == "viet nam" | `_from_clean' == "vietnam" | `_from_clean' == "north vietnam" | `_from_clean' == "democratic republic of vietnam"
replace `_names_std' = "Republic of Vietnam" if `_from_clean' == "republic of vietnam" | `_from_clean' == "south vietnam" | `_from_clean' == "vietnam republic of" | `_from_clean' == "south vietnam" | `_from_clean' == "republic of	south vietnam"
replace `_names_std' = "British Virgin Islands" if `_from_clean' == "british virgin islands" | `_from_clean' == "virgin islands uk" | `_from_clean' == "virgin islands british" | `_from_clean' == "br virgin is"
replace `_names_std' = "United States Virgin Islands" if `_from_clean' == "united states virgin islands" | `_from_clean' == "virgin islands us" | `_from_clean' == "us virgin islands"
replace `_names_std' = "Wallis and Futuna" if `_from_clean' == "wallis and futuna" | `_from_clean' == "wallis futuna" | `_from_clean' == "wallis and futuna islands" | `_from_clean' == "wallis futuna islands"
replace `_names_std' = "Western Sahara" if `_from_clean' == "western sahara"
replace `_names_std' = "Samoa" if `_from_clean' == "western samoa" | `_from_clean' == "samoa"
replace `_names_std' = "Wuerttemburg" if `_from_clean' == "wuerttemburg"
replace `_names_std' = "Yemen" if `_from_clean' == "yemen" | `_from_clean' == "yemen rep"
replace `_names_std' = "Yemen Arab Republic" if `_from_clean' == "yemen arab republic"	| `_from_clean' == "yemen arab republic former" | `_from_clean' == "yemen sanaa" | `_from_clean' == "north yemen" | `_from_clean' == "arab republic of yemen" | `_from_clean' == "yemen ar" | `_from_clean' == "yemen a r" | `_from_clean' == "yemen_n" | `_from_clean' == "yemen north" | `_from_clean' == "yemen north" | `_from_clean' == "yemen n"
replace `_names_std' = "Yemen People's Republic" if `_from_clean' == "yemen people's republic" | `_from_clean' == "democratic yemen former" | `_from_clean' == "yemen aden" | `_from_clean' == "south yemen" | `_from_clean' == "sourn yemen" | `_from_clean' == "yemen people's republic of" | `_from_clean' == "yemen p r" | `_from_clean' == "yemen pr" | `_from_clean' == "yemen_s" | `_from_clean' == "democratic yemen" | `_from_clean' == "yemen south" | `_from_clean' == "yemen south" | `_from_clean' == "yemen s"
replace `_names_std' = "Yugoslavia" if `_from_clean' == "yugoslavia" | `_from_clean' == "yugoslavia/serbia" | `_from_clean' == "serbia" | `_from_clean' == "serbia and montenegro" | `_from_clean' == "yugoslavia former socialist federal republic" | `_from_clean' == "yugoslavia8992"  | `_from_clean' == "yugoslav" | `_from_clean' == "serbia montenegro" | `_from_clean' == "socialist federal republic of yugoslavia" | `_from_clean' == "federal republic of yugoslavia"
replace `_names_std' = "Zambia" if `_from_clean' == "zambia"
replace `_names_std' = "Zanzibar" if `_from_clean' == "zanzibar"
replace `_names_std' = "Zimbabwe" if `_from_clean' == "zimbabwe" | `_from_clean' == "rhodesia" | `_from_clean' == "zimbabwe rhodesia"



* fill supplied variables with iso3c codes
replace `to_cl' = "AFG" if `_names_std'=="Afghanistan"
replace `to_cl' = "ALB" if `_names_std'=="Albania"
replace `to_cl' = "DZA" if `_names_std'=="Algeria"
replace `to_cl' = "ASM" if `_names_std'=="American Samoa"
replace `to_cl' = "AND" if `_names_std'=="Andorra"
replace `to_cl' = "AGO" if `_names_std'=="Angola"
replace `to_cl' = "AIA" if `_names_std'=="Anguilla"
replace `to_cl' = "ATG" if `_names_std'=="Antigua and Barbuda"
replace `to_cl' = "ARG" if `_names_std'=="Argentina"
replace `to_cl' = "ARM" if `_names_std'=="Armenia"
replace `to_cl' = "ABW" if `_names_std'=="Aruba"
replace `to_cl' = "AUS" if `_names_std'=="Australia"
replace `to_cl' = "AUT" if `_names_std'=="Austria"
replace `to_cl' = "AZE" if `_names_std'=="Azerbaijan"
replace `to_cl' = "BHS" if `_names_std'=="Bahamas"
replace `to_cl' = "BHR" if `_names_std'=="Bahrain"
replace `to_cl' = "BGD" if `_names_std'=="Bangladesh"
replace `to_cl' = "BRB" if `_names_std'=="Barbados"
replace `to_cl' = "BLR" if `_names_std'=="Belarus"
replace `to_cl' = "BEL" if `_names_std'=="Belgium"
replace `to_cl' = "BLZ" if `_names_std'=="Belize"
replace `to_cl' = "BEN" if `_names_std'=="Benin"
replace `to_cl' = "BMU" if `_names_std'=="Bermuda"
replace `to_cl' = "BTN" if `_names_std'=="Bhutan"
replace `to_cl' = "BOL" if `_names_std'=="Bolivia"
replace `to_cl' = "BES" if `_names_std'=="Bonaire"
replace `to_cl' = "BIH" if `_names_std'=="Bosnia and Herzegovina"
replace `to_cl' = "BWA" if `_names_std'=="Botswana"
replace `to_cl' = "BRA" if `_names_std'=="Brazil"
replace `to_cl' = "VGB" if `_names_std'=="British Virgin Islands"
replace `to_cl' = "BRN" if `_names_std'=="Brunei"
replace `to_cl' = "BGR" if `_names_std'=="Bulgaria"
replace `to_cl' = "BFA" if `_names_std'=="Burkina Faso"
replace `to_cl' = "BDI" if `_names_std'=="Burundi"
replace `to_cl' = "KHM" if `_names_std'=="Cambodia"
replace `to_cl' = "CMR" if `_names_std'=="Cameroon"
replace `to_cl' = "CAN" if `_names_std'=="Canada"
replace `to_cl' = "CPV" if `_names_std'=="Cape Verde"
replace `to_cl' = "CYM" if `_names_std'=="Cayman Islands"
replace `to_cl' = "CAF" if `_names_std'=="Central African Republic"
replace `to_cl' = "TCD" if `_names_std'=="Chad"
replace `to_cl' = "CHL" if `_names_std'=="Chile"
replace `to_cl' = "CHN" if `_names_std'=="China"
replace `to_cl' = "CXR" if `_names_std'=="Christmas Islands"
replace `to_cl' = "CCK" if `_names_std'=="Cocos Islands"
replace `to_cl' = "COL" if `_names_std'=="Colombia"
replace `to_cl' = "COM" if `_names_std'=="Comoros"
replace `to_cl' = "COG" if `_names_std'=="Congo"
replace `to_cl' = "COK" if `_names_std'=="Cook Islands"
replace `to_cl' = "CRI" if `_names_std'=="Costa Rica"
replace `to_cl' = "CIV" if `_names_std'=="Cote d'Ivoire"
replace `to_cl' = "HRV" if `_names_std'=="Croatia"
replace `to_cl' = "CUB" if `_names_std'=="Cuba"
replace `to_cl' = "CYP" if `_names_std'=="Cyprus"
replace `to_cl' = "CZE" if `_names_std'=="Czech Republic"
replace `to_cl' = "COD" if `_names_std'=="Democratic Republic of Congo"
replace `to_cl' = "DNK" if `_names_std'=="Denmark"
replace `to_cl' = "DJI" if `_names_std'=="Djibouti"
replace `to_cl' = "DMA" if `_names_std'=="Dominica"
replace `to_cl' = "DOM" if `_names_std'=="Dominican Republic"
replace `to_cl' = "ECU" if `_names_std'=="Ecuador"
replace `to_cl' = "EGY" if `_names_std'=="Egypt"
replace `to_cl' = "SLV" if `_names_std'=="El Salvador"
replace `to_cl' = "GNQ" if `_names_std'=="Equatorial Guinea"
replace `to_cl' = "ERI" if `_names_std'=="Eritrea"
replace `to_cl' = "EST" if `_names_std'=="Estonia"
replace `to_cl' = "ETH" if `_names_std'=="Ethiopia"
replace `to_cl' = "FRO" if `_names_std'=="Faeroe Islands"
replace `to_cl' = "FLK" if `_names_std'=="Falkland Islands"
replace `to_cl' = "FJI" if `_names_std'=="Fiji"
replace `to_cl' = "FIN" if `_names_std'=="Finland"
replace `to_cl' = "FRA" if `_names_std'=="France"
replace `to_cl' = "GUF" if `_names_std'=="French Guiana"
replace `to_cl' = "PYF" if `_names_std'=="French Polynesia"
replace `to_cl' = "GAB" if `_names_std'=="Gabon"
replace `to_cl' = "GMB" if `_names_std'=="Gambia"
replace `to_cl' = "GEO" if `_names_std'=="Georgia"
replace `to_cl' = "GDR" if `_names_std'=="German Democratic Republic"
replace `to_cl' = "DEU" if `_names_std'=="Germany"
replace `to_cl' = "GHA" if `_names_std'=="Ghana"
replace `to_cl' = "GIB" if `_names_std'=="Gibraltar"
replace `to_cl' = "GRC" if `_names_std'=="Greece"
replace `to_cl' = "GRL" if `_names_std'=="Greenland"
replace `to_cl' = "GRD" if `_names_std'=="Grenada"
replace `to_cl' = "GLP" if `_names_std'=="Guadeloupe"
replace `to_cl' = "GUM" if `_names_std'=="Guam"
replace `to_cl' = "GTM" if `_names_std'=="Guatemala"
replace `to_cl' = "GIN" if `_names_std'=="Guinea"
replace `to_cl' = "GNB" if `_names_std'=="Guinea-Bissau"
replace `to_cl' = "GUY" if `_names_std'=="Guyana"
replace `to_cl' = "HTI" if `_names_std'=="Haiti"
replace `to_cl' = "HND" if `_names_std'=="Honduras"
replace `to_cl' = "HKG" if `_names_std'=="Hong Kong"
replace `to_cl' = "HUN" if `_names_std'=="Hungary"
replace `to_cl' = "ISL" if `_names_std'=="Iceland"
replace `to_cl' = "IND" if `_names_std'=="India"
replace `to_cl' = "IDN" if `_names_std'=="Indonesia"
replace `to_cl' = "IRN" if `_names_std'=="Iran"
replace `to_cl' = "IRQ" if `_names_std'=="Iraq"
replace `to_cl' = "IRL" if `_names_std'=="Ireland"
replace `to_cl' = "ISR" if `_names_std'=="Israel"
replace `to_cl' = "ITA" if `_names_std'=="Italy"
replace `to_cl' = "JAM" if `_names_std'=="Jamaica"
replace `to_cl' = "JPN" if `_names_std'=="Japan"
replace `to_cl' = "JOR" if `_names_std'=="Jordan"
replace `to_cl' = "KAZ" if `_names_std'=="Kazakhstan"
replace `to_cl' = "KEN" if `_names_std'=="Kenya"
replace `to_cl' = "KIR" if `_names_std'=="Kiribati"
replace `to_cl' = "KWT" if `_names_std'=="Kuwait"
replace `to_cl' = "KGZ" if `_names_std'=="Kyrgyz Republic"
replace `to_cl' = "LAO" if `_names_std'=="Laos"
replace `to_cl' = "LVA" if `_names_std'=="Latvia"
replace `to_cl' = "LBN" if `_names_std'=="Lebanon"
replace `to_cl' = "LSO" if `_names_std'=="Lesotho"
replace `to_cl' = "LBR" if `_names_std'=="Liberia"
replace `to_cl' = "LBY" if `_names_std'=="Libya"
replace `to_cl' = "LIE" if `_names_std'=="Liechtenstein"
replace `to_cl' = "LTU" if `_names_std'=="Lithuania"
replace `to_cl' = "LUX" if `_names_std'=="Luxembourg"
replace `to_cl' = "MAC" if `_names_std'=="Macao"
replace `to_cl' = "MKD" if `_names_std'=="Macedonia"
replace `to_cl' = "MDG" if `_names_std'=="Madagascar"
replace `to_cl' = "MWI" if `_names_std'=="Malawi"
replace `to_cl' = "MYS" if `_names_std'=="Malaysia"
replace `to_cl' = "MDV" if `_names_std'=="Maldives"
replace `to_cl' = "MLI" if `_names_std'=="Mali"
replace `to_cl' = "MLT" if `_names_std'=="Malta"
replace `to_cl' = "MHL" if `_names_std'=="Marshall Islands"
replace `to_cl' = "MTQ" if `_names_std'=="Martinique"
replace `to_cl' = "MRT" if `_names_std'=="Mauritania"
replace `to_cl' = "MUS" if `_names_std'=="Mauritius"
replace `to_cl' = "MYT" if `_names_std'=="Mayotte"
replace `to_cl' = "MEX" if `_names_std'=="Mexico"
replace `to_cl' = "FSM" if `_names_std'=="Micronesia"
replace `to_cl' = "MDA" if `_names_std'=="Moldova"
replace `to_cl' = "MCO" if `_names_std'=="Monaco"
replace `to_cl' = "MNG" if `_names_std'=="Mongolia"
replace `to_cl' = "MNE" if `_names_std'=="Montenegro"
replace `to_cl' = "MSR" if `_names_std'=="Montserrat"
replace `to_cl' = "MAR" if `_names_std'=="Morocco"
replace `to_cl' = "MOZ" if `_names_std'=="Mozambique"
replace `to_cl' = "MMR" if `_names_std'=="Myanmar"
replace `to_cl' = "NAM" if `_names_std'=="Namibia"
replace `to_cl' = "NRU" if `_names_std'=="Nauru"
replace `to_cl' = "NPL" if `_names_std'=="Nepal"
replace `to_cl' = "NLD" if `_names_std'=="Netherlands"
replace `to_cl' = "ANT" if `_names_std'=="Netherlands Antilles"
replace `to_cl' = "NCL" if `_names_std'=="New Caledonia"
replace `to_cl' = "NZL" if `_names_std'=="New Zealand"
replace `to_cl' = "NIC" if `_names_std'=="Nicaragua"
replace `to_cl' = "NER" if `_names_std'=="Niger"
replace `to_cl' = "NGA" if `_names_std'=="Nigeria"
replace `to_cl' = "NIU" if `_names_std'=="Niue"
replace `to_cl' = "PRK" if `_names_std'=="North Korea"
replace `to_cl' = "NOR" if `_names_std'=="Norway"
replace `to_cl' = "OMN" if `_names_std'=="Oman"
replace `to_cl' = "PAK" if `_names_std'=="Pakistan"
replace `to_cl' = "PLW" if `_names_std'=="Palau"
replace `to_cl' = "PSE" if `_names_std'=="Palestine"
replace `to_cl' = "PAN" if `_names_std'=="Panama"
replace `to_cl' = "PNG" if `_names_std'=="Papua New Guinea"
replace `to_cl' = "PRY" if `_names_std'=="Paraguay"
replace `to_cl' = "PER" if `_names_std'=="Peru"
replace `to_cl' = "PHL" if `_names_std'=="Philippines"
replace `to_cl' = "POL" if `_names_std'=="Poland"
replace `to_cl' = "PRT" if `_names_std'=="Portugal"
replace `to_cl' = "PRI" if `_names_std'=="Puerto Rico"
replace `to_cl' = "QAT" if `_names_std'=="Qatar"
replace `to_cl' = "VNM" if `_names_std'=="Republic of Vietnam"
replace `to_cl' = "REU" if `_names_std'=="Reunion"
replace `to_cl' = "ROU" if `_names_std'=="Romania"
replace `to_cl' = "RUS" if `_names_std'=="Russia"
replace `to_cl' = "RWA" if `_names_std'=="Rwanda"
replace `to_cl' = "SHN" if `_names_std'=="Saint Helena"
replace `to_cl' = "KNA" if `_names_std'=="Saint Kitts and Nevis"
replace `to_cl' = "LCA" if `_names_std'=="Saint Lucia"
replace `to_cl' = "SPM" if `_names_std'=="Saint Pierre and Miquelon"
replace `to_cl' = "VCT" if `_names_std'=="Saint Vincent and the Grenadines"
replace `to_cl' = "WSM" if `_names_std'=="Samoa"
replace `to_cl' = "SMR" if `_names_std'=="San Marino"
replace `to_cl' = "STP" if `_names_std'=="Sao Tome and Principe"
replace `to_cl' = "SAU" if `_names_std'=="Saudi Arabia"
replace `to_cl' = "SEN" if `_names_std'=="Senegal"
replace `to_cl' = "SYC" if `_names_std'=="Seychelles"
replace `to_cl' = "SLE" if `_names_std'=="Sierra Leone"
replace `to_cl' = "SGP" if `_names_std'=="Singapore"
replace `to_cl' = "SVK" if `_names_std'=="Slovak Republic"
replace `to_cl' = "SVN" if `_names_std'=="Slovenia"
replace `to_cl' = "SLB" if `_names_std'=="Solomon Islands"
replace `to_cl' = "SOM" if `_names_std'=="Somalia"
replace `to_cl' = "ZAF" if `_names_std'=="South Africa"
replace `to_cl' = "KOR" if `_names_std'=="South Korea"
replace `to_cl' = "SSD" if `_names_std'=="South Sudan"
replace `to_cl' = "ESP" if `_names_std'=="Spain"
replace `to_cl' = "LKA" if `_names_std'=="Sri Lanka"
replace `to_cl' = "SDN" if `_names_std'=="Sudan"
replace `to_cl' = "SUR" if `_names_std'=="Suriname"
replace `to_cl' = "SWZ" if `_names_std'=="Swaziland"
replace `to_cl' = "SWE" if `_names_std'=="Sweden"
replace `to_cl' = "CHE" if `_names_std'=="Switzerland"
replace `to_cl' = "SYR" if `_names_std'=="Syria"
replace `to_cl' = "TWN" if `_names_std'=="Taiwan"
replace `to_cl' = "TJK" if `_names_std'=="Tajikistan"
replace `to_cl' = "TZA" if `_names_std'=="Tanzania"
replace `to_cl' = "THA" if `_names_std'=="Thailand"
replace `to_cl' = "TLS" if `_names_std'=="Timor"
replace `to_cl' = "TGO" if `_names_std'=="Togo"
replace `to_cl' = "TON" if `_names_std'=="Tonga"
replace `to_cl' = "TTO" if `_names_std'=="Trinidad and Tobago"
replace `to_cl' = "TUN" if `_names_std'=="Tunisia"
replace `to_cl' = "TUR" if `_names_std'=="Turkey"
replace `to_cl' = "TKM" if `_names_std'=="Turkmenistan"
replace `to_cl' = "TCA" if `_names_std'=="Turks and Caicos Islands"
replace `to_cl' = "TUV" if `_names_std'=="Tuvalu"
replace `to_cl' = "UGA" if `_names_std'=="Uganda"
replace `to_cl' = "UKR" if `_names_std'=="Ukraine"
replace `to_cl' = "ARE" if `_names_std'=="United Arab Emirates"
replace `to_cl' = "GBR" if `_names_std'=="United Kingdom"
replace `to_cl' = "USA" if `_names_std'=="United States"
replace `to_cl' = "VIR" if `_names_std'=="United States Virgin Islands"
replace `to_cl' = "URY" if `_names_std'=="Uruguay"
replace `to_cl' = "UZB" if `_names_std'=="Uzbekistan"
replace `to_cl' = "VUT" if `_names_std'=="Vanuatu"
replace `to_cl' = "VAT" if `_names_std'=="Vatican"
replace `to_cl' = "VEN" if `_names_std'=="Venezuela"
replace `to_cl' = "VNM" if `_names_std'=="Vietnam"
replace `to_cl' = "WLF" if `_names_std'=="Wallis and Futuna"
replace `to_cl' = "ESH" if `_names_std'=="Western Sahara"
replace `to_cl' = "YEM" if `_names_std'=="Yemen"
replace `to_cl' = "SRB" if `_names_std'=="Yugoslavia"
replace `to_cl' = "ZMB" if `_names_std'=="Zambia"
replace `to_cl' = "ZWE" if `_names_std'=="Zimbabwe"

end
exit
